### PR TITLE
[DEV-11397] Long text with button causes the button overflow outside the story container in themes

### PR DESCRIPTION
**Pull request by fgyimah**

### CODE REVIEW

**Review by e1himself — APPROVED** [review]

**Comment by fgyimah** [comment]
@e1himself the failing story isn't related to this PR, okay to update anyways? (It passes in local too)
Screenshot 2023-08-17 at 10 27 31 AM

**Comment by e1himself** [comment]
@fgyimah Alright :+1:

**Comment by fgyimah** [comment]
> @fgyimah Alright 👍

Updating returns same screenshot, and it pass locally, not sure why it fails here

**Comment by fgyimah** [comment]
> > @fgyimah Alright 👍
> 
> Updating returns same screenshot, and it passes locally, not sure why it fails here

Should we merge now to unblock ticket and fix this later?

**Comment by fgyimah** [comment]
> > > @fgyimah Alright 👍
> > 
> > 
> > Updating returns same screenshot, and it passes locally, not sure why it fails here
> 
> Should we merge now to unblock ticket and fix this later?

Strange enough, after merging, it passed in [master branch](https://github.com/prezly/content-renderer-react-js/actions/runs/5890098571/job/15974544170)

**Pull request merged**
